// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYGaNNt357hB-WyvdELtsu68AeYdW_PP0',
    appId: '1:701801154584:web:bee3ea13542245b5b91b6d',
    messagingSenderId: '701801154584',
    projectId: 'ojtconnect-cca5b',
    authDomain: 'ojtconnect-cca5b.firebaseapp.com',
    storageBucket: 'ojtconnect-cca5b.firebasestorage.app',
    measurementId: 'G-4HBJEY0MM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsFAYC56SNqprm0JcRK6U6U8ZXwbiG1Q',
    appId: '1:701801154584:android:0cb8bba95dedbe7eb91b6d',
    messagingSenderId: '701801154584',
    projectId: 'ojtconnect-cca5b',
    storageBucket: 'ojtconnect-cca5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHG2u5hYgpqBWJYsAoaCKUjOuQEdgfFFk',
    appId: '1:701801154584:ios:800a238d1be134b8b91b6d',
    messagingSenderId: '701801154584',
    projectId: 'ojtconnect-cca5b',
    storageBucket: 'ojtconnect-cca5b.firebasestorage.app',
    iosBundleId: 'com.example.ojtConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHG2u5hYgpqBWJYsAoaCKUjOuQEdgfFFk',
    appId: '1:701801154584:ios:800a238d1be134b8b91b6d',
    messagingSenderId: '701801154584',
    projectId: 'ojtconnect-cca5b',
    storageBucket: 'ojtconnect-cca5b.firebasestorage.app',
    iosBundleId: 'com.example.ojtConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYGaNNt357hB-WyvdELtsu68AeYdW_PP0',
    appId: '1:701801154584:web:f4147e0c56135284b91b6d',
    messagingSenderId: '701801154584',
    projectId: 'ojtconnect-cca5b',
    authDomain: 'ojtconnect-cca5b.firebaseapp.com',
    storageBucket: 'ojtconnect-cca5b.firebasestorage.app',
    measurementId: 'G-9DQ7VL0BFL',
  );
}
